blogger:
  username: joshcarter2006@gmail.com
  password: fptk5rzP
  blog_id: 10881293
  login_url: https://www.google.com:443/accounts/ClientLogin

twitter:
  username: bobtheman
  password: vedBEpR7kuU3wk
